import { test, expect, describe } from 'bun:test';
import { execSync } from 'child_process';
import { mkdtemp, rm } from 'fs/promises';
import { join } from 'path';
import { tmpdir } from 'os';
import { writeFileSync, readFileSync } from 'fs';

describe('Metadata preservation in themes', () => {
  test('OpenCode themes store _ghosttyName metadata', async () => {
    const { writeOpenCodeTheme } = await import('../src/opencode');
    const tmpDir = await mkdtemp(join(tmpdir(), 'ghostpencode-'));

    const testCases = [
      { ghosttyName: 'Black Metal (Burzum)', opencodeFilename: 'black-metal-burzum' },
      { ghosttyName: 'GitHub', opencodeFilename: 'github' },
      { ghosttyName: '12-bit Rainbow', opencodeFilename: '12-bit-rainbow' },
      { ghosttyName: 'Dark+', opencodeFilename: 'dark' },
    ];

    for (const { ghosttyName, opencodeFilename } of testCases) {
      const testPalette = {
        background: '#000000',
        foreground: '#ffffff',
        cursor: '#ffffff',
        selection: '#404040',
        black: '#000000',
        red: '#cc0000',
        green: '#00cc00',
        yellow: '#cccc00',
        blue: '#0000cc',
        magenta: '#cc00cc',
        cyan: '#00cccc',
        white: '#cccccc',
        brightBlack: '#808080',
        brightRed: '#ff0000',
        brightGreen: '#00ff00',
        brightYellow: '#ffff00',
        brightBlue: '#0000ff',
        brightMagenta: '#ff00ff',
        brightCyan: '#00ffff',
        brightWhite: '#ffffff',
      };

      // Write theme with metadata
      const themePath = join(tmpDir, `${opencodeFilename}.json`);
      writeFileSync(themePath, JSON.stringify({
        $schema: 'https://opencode.ai/theme.json',
        _ghosttyName: ghosttyName,
        defs: {
          bg: testPalette.background,
          fg: testPalette.foreground,
        },
        theme: {}
      }, null, 2));

      // Read it back
      const content = JSON.parse(readFileSync(themePath, 'utf-8'));

      expect(content._ghosttyName).toBe(ghosttyName);
    }

    await rm(tmpDir, { recursive: true, force: true });
  });

  test('Ghostty themes store OpenCode filename in comment', async () => {
    const { writeGhosttyTheme } = await import('../src/ghostty');
    const tmpDir = await mkdtemp(join(tmpdir(), 'ghostpencode-'));

    const testCases = [
      { ghosttyName: 'Black Metal (Burzum)', opencodeFilename: 'black-metal-burzum' },
      { ghosttyName: 'GitHub', opencodeFilename: 'github' },
    ];

    for (const { ghosttyName, opencodeFilename } of testCases) {
      const testPalette = {
        background: '#000000',
        foreground: '#ffffff',
        cursor: '#ffffff',
        selection: '#404040',
        black: '#000000',
        red: '#cc0000',
        green: '#00cc00',
        yellow: '#cccc00',
        blue: '#0000cc',
        magenta: '#cc00cc',
        cyan: '#00cccc',
        white: '#cccccc',
        brightBlack: '#808080',
        brightRed: '#ff0000',
        brightGreen: '#00ff00',
        brightYellow: '#ffff00',
        brightBlue: '#0000ff',
        brightMagenta: '#ff00ff',
        brightCyan: '#00ffff',
        brightWhite: '#ffffff',
      };

      // Write theme with metadata
      const themePath = join(tmpDir, ghosttyName);
      const content = `# ${ghosttyName}
# Generated by ghostpencode
# OpenCode filename: ${opencodeFilename}

palette = 0=${testPalette.black}
background = ${testPalette.background}
foreground = ${testPalette.foreground}
`;
      writeFileSync(themePath, content);

      // Read it back
      const readContent = readFileSync(themePath, 'utf-8');
      const lines = readContent.split('\n');

      let foundFilename: string | null = null;
      for (const line of lines) {
        if (line.trim().startsWith('# OpenCode filename:')) {
          foundFilename = line.trim().replace('# OpenCode filename:', '').trim();
          break;
        }
      }

      expect(foundFilename).toBe(opencodeFilename);
    }

    await rm(tmpDir, { recursive: true, force: true });
  });

  test('Problem themes from Ghostty list', async () => {
    // Get a sample of problem themes from Ghostty
    const themesOutput = execSync('ghostty +list-themes', { encoding: 'utf-8' });
    const problemThemes = [
      '12-bit Rainbow',
      'Black Metal (Burzum)',
      'GitHub',
      'Dark+',
      'Hopscotch.256',
      'TokyoNight',
      'iTerm2 Dark Background',
    ];

    const { toKebabCase } = await import('../src/utils');

    const conversions = problemThemes.map(theme => ({
      original: theme,
      kebab: toKebabCase(theme),
    }));

    console.log('\nProblem theme conversions:');
    for (const { original, kebab } of conversions) {
      console.log(`  "${original}" → "${kebab}"`);
    }

    // All should have valid kebab-case filenames
    for (const { kebab } of conversions) {
      expect(kebab).toMatch(/^[a-z0-9-]+$/);
    }
  });
});
