import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';
import type { Palette } from './types';

const GHOSTTY_CONFIG_PATHS = [
  join(homedir(), 'Library/Application Support/com.mitchellh.ghostty/config'),
  join(homedir(), '.config/ghostty/config'),
];

const GHOSTTY_THEMES_DIR = join('/Applications/Ghostty.app/Contents/Resources/ghostty/themes');

function getGhosttyConfigPath(): string | null {
  for (const path of GHOSTTY_CONFIG_PATHS) {
    if (existsSync(path)) return path;
  }
  return null;
}

export function getCurrentGhosttyTheme(): string | null {
  const configPath = getGhosttyConfigPath();
  if (!configPath) return null;

  const config = readFileSync(configPath, 'utf-8');
  const match = config.match(/^theme\s*=\s*(.+)$/m);
  return match ? match[1].trim() : null;
}

export function readGhosttyTheme(themeName: string): Palette | null {
  const themePath = join(GHOSTTY_THEMES_DIR, themeName);
  if (!existsSync(themePath)) return null;

  const content = readFileSync(themePath, 'utf-8');
  const lines = content.split('\n');
  
  const palette: any = {};
  const paletteMap: any = {};

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const [key, value] = trimmed.split('=').map(s => s.trim());
    if (!key || !value) continue;

    if (key === 'background') palette.background = value;
    else if (key === 'foreground') palette.foreground = value;
    else if (key === 'cursor-color') palette.cursor = value;
    else if (key === 'selection-background') palette.selection = value;
    else if (key.startsWith('palette')) {
      const num = parseInt(key.split('=')[0].match(/\d+/)?.[0] || '0');
      paletteMap[num] = value;
    }
  }

  return {
    background: palette.background || '#000000',
    foreground: palette.foreground || '#ffffff',
    cursor: palette.cursor || palette.foreground || '#ffffff',
    selection: palette.selection || '#404040',
    black: paletteMap[0] || '#000000',
    red: paletteMap[1] || '#cc0000',
    green: paletteMap[2] || '#00cc00',
    yellow: paletteMap[3] || '#cccc00',
    blue: paletteMap[4] || '#0000cc',
    magenta: paletteMap[5] || '#cc00cc',
    cyan: paletteMap[6] || '#00cccc',
    white: paletteMap[7] || '#cccccc',
    brightBlack: paletteMap[8] || '#808080',
    brightRed: paletteMap[9] || '#ff0000',
    brightGreen: paletteMap[10] || '#00ff00',
    brightYellow: paletteMap[11] || '#ffff00',
    brightBlue: paletteMap[12] || '#0000ff',
    brightMagenta: paletteMap[13] || '#ff00ff',
    brightCyan: paletteMap[14] || '#00ffff',
    brightWhite: paletteMap[15] || '#ffffff',
  };
}

export function writeGhosttyConfig(themeName: string, palette: Palette): void {
  const configPath = getGhosttyConfigPath();
  if (!configPath) {
    throw new Error('Could not find Ghostty config file');
  }

  let config = existsSync(configPath) ? readFileSync(configPath, 'utf-8') : '';
  
  // Update or add theme line
  if (config.match(/^theme\s*=/m)) {
    config = config.replace(/^theme\s*=.*$/m, `theme = ${themeName}`);
  } else {
    config += `\ntheme = ${themeName}\n`;
  }

  writeFileSync(configPath, config, 'utf-8');
}

export function writeGhosttyTheme(themeName: string, palette: Palette): string {
  const themesDir = join(homedir(), '.config/ghostty/themes');
  
  if (!existsSync(themesDir)) {
    mkdirSync(themesDir, { recursive: true });
  }

  const themePath = join(themesDir, themeName);
  
  const content = `# ${themeName}
# Generated by ghostpencode

palette = 0=${palette.black}
palette = 1=${palette.red}
palette = 2=${palette.green}
palette = 3=${palette.yellow}
palette = 4=${palette.blue}
palette = 5=${palette.magenta}
palette = 6=${palette.cyan}
palette = 7=${palette.white}
palette = 8=${palette.brightBlack}
palette = 9=${palette.brightRed}
palette = 10=${palette.brightGreen}
palette = 11=${palette.brightYellow}
palette = 12=${palette.brightBlue}
palette = 13=${palette.brightMagenta}
palette = 14=${palette.brightCyan}
palette = 15=${palette.brightWhite}
background = ${palette.background}
foreground = ${palette.foreground}
cursor-color = ${palette.cursor}
cursor-text = ${palette.background}
selection-background = ${palette.selection}
selection-foreground = ${palette.foreground}
`;

  writeFileSync(themePath, content, 'utf-8');
  return themePath;
}
